# Site settings
title: Contact Page
description: Software/Web development portfolio for Marc Visser
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://marcvisser.eu" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marc Visser
user_description: Experienced Software Engineer with a demonstrated history of working in the computer software industry. Skilled in full-stack web development, big data, data analytics. End bachelor engineering student currently working on a Bachelor of Applied Science (BASc) focused in Computer Science from Delft University of Technology.
user_title: Software Developer
email: marcvisser@outlook.com
twitter_username: bugorfeature 
github_username:  bugorfeature
gplus_username: bugorfeature

# Google-analytics
google-analytics:
  id: "UA-114296280-1"

exclude: ['package.json', 'src' , 'node_modules']
